Wrapping up possible crashes
HorizenOfficial/zendoo-cctp-lib pull request #23
Opened 2021-08-11 05:22 UTC by phoinic

Wrapped cases:

- "unwrap" usage - can cause panics
- assertions in parameters check - can cause panics
- direct calls of "panic!"

2021-08-30 10:02 UTC, DanieleDiBenedetto requested changes

2021-08-30 10:02 UTC, DanieleDiBenedetto commented on cctp_primitives/src/utils/mod.rs
> +            if bt_fes.len() != 1 {
Let's leave the assertion here

2021-08-30 10:02 UTC, DanieleDiBenedetto commented on cctp_primitives/src/utils/mod.rs
> +    if fees_field_elements.len() != 1 {
Let's leave the assertion here

2021-08-30 12:10 UTC, phoinic commented on cctp_primitives/src/utils/mod.rs
> +            if bt_fes.len() != 1 {
Done

2021-08-30 12:11 UTC, phoinic commented on cctp_primitives/src/utils/mod.rs
> +    if fees_field_elements.len() != 1 {
Done

2021-08-30 12:35 UTC, DanieleDiBenedetto approved these changes

2021-09-01 16:14 UTC, DanieleDiBenedetto commented
@i-Alex if you can take a look at it too would be great. Some interfaces have slightly changed (mostly returning Err or Option because we removed some dangerous unwraps).
A parallel PR is opened on zendoo-sc-cryptolib too (https://github.com/HorizenOfficial/zendoo-sc-cryptolib/pull/61).
Please be aware of these changes when reporting them into the SDK (shouldn't be a huge deal).

2021-09-02 08:37 UTC, i-Alex approved these changes

2021-10-06 13:31 UTC, merged