Sc key rotation
HorizenOfficial/zendoo-cctp-lib pull request #44
Opened 2022-10-04 14:58 UTC by a-petrini

Adding additional field to CertificateProofUserInputs to support key rotation feature

2022-10-05 11:00 UTC, ptagl approved these changes

2022-10-05 11:00 UTC, ptagl commented on cctp_primitives/src/proving_system/verifier/certificate.rs
> +        // the library itself.
Can we get rid of this comment now?

```suggestion
```

2022-10-05 12:33 UTC, DanieleDiBenedetto requested changes

2022-10-05 12:33 UTC, DanieleDiBenedetto commented on cctp_primitives/src/proving_system/verifier/certificate.rs
> +        if self.sc_prev_wcert_hash.is_some() {
Unless you are handling it differently on MC-cryptolib side in order to avoid code duplication here

2022-10-06 10:17 UTC, ptagl commented on cctp_primitives/src/proving_system/verifier/certificate.rs
> +        if self.sc_prev_wcert_hash.is_some() {
PHANTOM_CERT_DATA_HASH is passed directly by Zend when dealing with the certificate of the first epoch for non-ceasable sidechains.

2022-10-07 08:25 UTC, DanieleDiBenedetto approved these changes

2022-10-07 08:28 UTC, merged